"""empty message

Revision ID: 022399dac5dc
Revises: 25a42da13fba
Create Date: 2023-05-12 15:21:26.458014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022399dac5dc'
down_revision = '25a42da13fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
